// Mock data để khởi tạo ứng dụng
import type { Course, Exercise, Quiz } from '../types';
import { saveCourses, saveExercises, saveQuizzes } from './storage';

export const initializeMockData = (): void => {
  // Mock Courses
  const courses: Course[] = [
    {
      id: 'course-1',
      name: 'Tiếng Anh 1',
      code: 'ENG101',
      description: 'Học phần Tiếng Anh 1 dành cho sinh viên đại học',
      lessons: [
        {
          id: 'lesson-1-1',
          courseId: 'course-1',
          title: 'Unit 1: Greetings and Introductions',
          order: 1,
          slides: [
            {
              id: 'slide-1-1-1',
              lessonId: 'lesson-1-1',
              title: 'Slide bài học',
              fileUrl: '/silde.pptx',
              order: 1,
            },
          ],
          videos: [
            {
              id: 'video-1-1-1',
              lessonId: 'lesson-1-1',
              title: 'Video bài học',
              url: '/video.mp4',
              duration: 300,
              order: 1,
            },
          ],
          references: [
            {
              id: 'ref-1-1-1',
              lessonId: 'lesson-1-1',
              title: 'Word List',
              type: 'pdf',
              url: '/WordList.pdf',
            },
          ],
        },
        {
          id: 'lesson-1-2',
          courseId: 'course-1',
          title: 'Unit 2: Present Simple Tense',
          order: 2,
          slides: [],
          videos: [],
          references: [],
        },
      ],
    },
    {
      id: 'course-2',
      name: 'Tiếng Anh 2',
      code: 'ENG102',
      description: 'Học phần Tiếng Anh 2 dành cho sinh viên đại học',
      lessons: [
        {
          id: 'lesson-2-1',
          courseId: 'course-2',
          title: 'Unit 1: Past Simple Tense',
          order: 1,
          slides: [],
          videos: [],
          references: [],
        },
        {
          id: 'lesson-2-2',
          courseId: 'course-2',
          title: 'Unit 2: Future Tense',
          order: 2,
          slides: [],
          videos: [],
          references: [],
        },
      ],
    },
  ];

  // Mock Exercises – chỉ 1 bài hoàn chỉnh gồm 7 phần giống các hình
  const exercises: Exercise[] = [
    {
      id: 'exercise-unit1',
      courseId: 'course-1',
      title: 'Unit 1 – Grammar, Vocabulary & Skills',
      sections: [
        // 1. Grammar Bank 1A – sửa câu hỏi
        {
          id: 'unit1-sec-1',
          title: 'Grammar Bank 1A – Question forms',
          sectionType: 'grammar',
          questionType: 'fill-sentence',
          questions: [
            {
              id: 'u1-s1-q1',
              sectionId: 'unit1-sec-1',
              question: 'Rewrite: "Where the train station?" (is)',
              type: 'fill-sentence',
              correctAnswer: 'Where is the train station?',
              points: 5,
            },
            {
              id: 'u1-s1-q2',
              sectionId: 'unit1-sec-1',
              question: 'Rewrite: "How often you read magazines?" (do)',
              type: 'fill-sentence',
              correctAnswer: 'How often do you read magazines?',
              points: 5,
            },
            {
              id: 'u1-s1-q3',
              sectionId: 'unit1-sec-1',
              question: 'Rewrite: "Do you often to the cinema?" (go)',
              type: 'fill-sentence',
              correctAnswer: 'Do you often go to the cinema?',
              points: 5,
            },
            {
              id: 'u1-s1-q4',
              sectionId: 'unit1-sec-1',
              question: 'Rewrite: "What this word mean?" (does)',
              type: 'fill-sentence',
              correctAnswer: 'What does this word mean?',
              points: 5,
            },
            {
              id: 'u1-s1-q5',
              sectionId: 'unit1-sec-1',
              question: 'Rewrite: "What time did arrive?" (your friends)',
              type: 'fill-sentence',
              correctAnswer: 'What time did your friends arrive?',
              points: 5,
            },
            {
              id: 'u1-s1-q6',
              sectionId: 'unit1-sec-1',
              question: 'Rewrite: "When I see you?" (can)',
              type: 'fill-sentence',
              correctAnswer: 'When can I see you?',
              points: 5,
            },
          ],
        },
        // 2. Put the words in the correct order
        {
          id: 'unit1-sec-2',
          title: 'Make questions – word order',
          sectionType: 'grammar',
          questionType: 'word-order',
          questions: [
            {
              id: 'u1-s2-q1',
              sectionId: 'unit1-sec-2',
              question: 'a / you / do / have / car?',
              type: 'word-order',
              correctAnswer: 'Do you have a car?',
              points: 5,
            },
            {
              id: 'u1-s2-q2',
              sectionId: 'unit1-sec-2',
              question: 'your / a / father / doctor / is',
              type: 'word-order',
              correctAnswer: 'Is your father a doctor?',
              points: 5,
            },
            {
              id: 'u1-s2-q3',
              sectionId: 'unit1-sec-2',
              question: 'Italian / you / can / speak',
              type: 'word-order',
              correctAnswer: 'Can you speak Italian?',
              points: 5,
            },
            {
              id: 'u1-s2-q4',
              sectionId: 'unit1-sec-2',
              question: 'where / summer / you / did / go / last',
              type: 'word-order',
              correctAnswer: 'Where did you go last summer?',
              points: 5,
            },
            {
              id: 'u1-s2-q5',
              sectionId: 'unit1-sec-2',
              question: 'were / you / born / where',
              type: 'word-order',
              correctAnswer: 'Where were you born?',
              points: 5,
            },
            {
              id: 'u1-s2-q6',
              sectionId: 'unit1-sec-2',
              question: 'your / what / class / does / start / time',
              type: 'word-order',
              correctAnswer: 'What time does your class start?',
              points: 5,
            },
          ],
        },
        // 3. Choose the correct verbs. Then listen and check.
        {
          id: 'unit1-sec-3',
          title: 'Choose the correct verbs. Then listen and check.',
          sectionType: 'listening',
          questionType: 'dropdown-choice',
          audioUrl: 'https://example.com/audio/unit1-choose-verbs.mp3',
          questions: [
            {
              id: 'u1-s3-q1',
              sectionId: 'unit1-sec-3',
              question: 'Where ____ you from?',
              type: 'dropdown-choice',
              options: ['are', 'do', 'were'],
              correctAnswer: 'are',
              points: 5,
            },
            {
              id: 'u1-s3-q2',
              sectionId: 'unit1-sec-1',
              question: 'Where ____ you born?',
              type: 'dropdown-choice',
              options: ['are', 'do', 'were'],
              correctAnswer: 'were',
              points: 5,
            },
            {
              id: 'u1-s3-q3',
              sectionId: 'unit1-sec-1',
              question: 'Where do you ____?',
              type: 'dropdown-choice',
              options: ['live', 'are', 'have'],
              correctAnswer: 'live',
              points: 5,
            },
            {
              id: 'u1-s3-q4',
              sectionId: 'unit1-sec-1',
              question: 'Do you ____ in a house or a flat?',
              type: 'dropdown-choice',
              options: ['live', 'are', 'have'],
              correctAnswer: 'live',
              points: 5,
            },
            {
              id: 'u1-s3-q5',
              sectionId: 'unit1-sec-1',
              question: 'Do you ____ any brothers and sisters?',
              type: 'dropdown-choice',
              options: ['have', 'are', 'do'],
              correctAnswer: 'have',
              points: 5,
            },
            {
              id: 'u1-s3-q6',
              sectionId: 'unit1-sec-1',
              question: 'Do you ____ any pets?',
              type: 'dropdown-choice',
              options: ['have', 'are', 'do'],
              correctAnswer: 'have',
              points: 5,
            },
            {
              id: 'u1-s3-q7',
              sectionId: 'unit1-sec-1',
              question: 'What do you ____?',
              type: 'dropdown-choice',
              options: ['do', 'are', 'have'],
              correctAnswer: 'do',
              points: 5,
            },
            {
              id: 'u1-s3-q8',
              sectionId: 'unit1-sec-1',
              question: 'What time do you ____ up during the week?',
              type: 'dropdown-choice',
              options: ['get', 'go', 'wake'],
              correctAnswer: 'get',
              points: 5,
            },
          ],
        },
        // 4. Complete the sentences with verbs in the box
        {
          id: 'unit1-sec-4',
          title: 'Complete the sentences with verbs in the box',
          sectionType: 'vocabulary',
          questionType: 'fill-blank',
          wordBank: ['go', 'study', 'do', 'go', 'watch', 'listen', 'read', 'speak', 'do', 'have'],
          questions: [
            {
              id: 'u1-s4-q1',
              sectionId: 'unit1-sec-4',
              question: 'Where do you usually ____ lunch?',
              type: 'fill-blank',
              correctAnswer: 'have',
              points: 5,
            },
            {
              id: 'u1-s4-q2',
              sectionId: 'unit1-sec-1',
              question: 'What time do you usually ____ to bed?',
              type: 'fill-blank',
              correctAnswer: 'go',
              points: 5,
            },
            {
              id: 'u1-s4-q3',
              sectionId: 'unit1-sec-1',
              question: 'Where did you ____ English before?',
              type: 'fill-blank',
              correctAnswer: 'study',
              points: 5,
            },
            {
              id: 'u1-s4-q4',
              sectionId: 'unit1-sec-1',
              question: 'Can you ____ any other languages? Which?',
              type: 'fill-blank',
              correctAnswer: 'speak',
              points: 5,
            },
            {
              id: 'u1-s4-q5',
              sectionId: 'unit1-sec-1',
              question: 'What kind of music do you ____ to?',
              type: 'fill-blank',
              correctAnswer: 'listen',
              points: 5,
            },
            {
              id: 'u1-s4-q6',
              sectionId: 'unit1-sec-1',
              question: 'What TV programmes or series do you ____?',
              type: 'fill-blank',
              correctAnswer: 'watch',
              points: 5,
            },
            {
              id: 'u1-s4-q7',
              sectionId: 'unit1-sec-1',
              question: 'Do you ____ any sport or exercise? What?',
              type: 'fill-blank',
              correctAnswer: 'do',
              points: 5,
            },
            {
              id: 'u1-s4-q8',
              sectionId: 'unit1-sec-1',
              question: 'What kind of books or magazines do you ____?',
              type: 'fill-blank',
              correctAnswer: 'read',
              points: 5,
            },
            {
              id: 'u1-s4-q9',
              sectionId: 'unit1-sec-1',
              question: 'How often do you ____ to the cinema?',
              type: 'fill-blank',
              correctAnswer: 'go',
              points: 5,
            },
          ],
        },
        // 5. Pronunciation – vowel sounds
        {
          id: 'unit1-sec-5',
          title: 'Pronunciation – vowel sounds',
          sectionType: 'pronunciation',
          questionType: 'pronunciation',
          audioUrl: 'https://example.com/audio/unit1-vowel-sounds.mp3',
          imageUrl: 'https://example.com/images/unit1-vowel-sounds-chart.png',
          questions: [
            {
              id: 'u1-s5-q1',
              sectionId: 'unit1-sec-5',
              question: 'Say the word: train /eɪ/',
              type: 'pronunciation',
              imageUrl: 'https://example.com/images/unit1-train.png',
              correctAnswer: 'train',
              points: 5,
            },
            {
              id: 'u1-s5-q2',
              sectionId: 'unit1-sec-1',
              question: 'Say the word: tree /iː/',
              type: 'pronunciation',
              imageUrl: 'https://example.com/images/unit1-tree.png',
              correctAnswer: 'tree',
              points: 5,
            },
            {
              id: 'u1-s5-q3',
              sectionId: 'unit1-sec-1',
              question: 'Say the word: egg /e/',
              type: 'pronunciation',
              imageUrl: 'https://example.com/images/unit1-egg.png',
              correctAnswer: 'egg',
              points: 5,
            },
            {
              id: 'u1-s5-q4',
              sectionId: 'unit1-sec-1',
              question: 'Say the word: bike /aɪ/',
              type: 'pronunciation',
              imageUrl: 'https://example.com/images/unit1-bike.png',
              correctAnswer: 'bike',
              points: 5,
            },
            {
              id: 'u1-s5-q5',
              sectionId: 'unit1-sec-1',
              question: 'Say the word: phone /əʊ/',
              type: 'pronunciation',
              imageUrl: 'https://example.com/images/unit1-phone.png',
              correctAnswer: 'phone',
              points: 5,
            },
            {
              id: 'u1-s5-q6',
              sectionId: 'unit1-sec-1',
              question: 'Say the word: boot /uː/',
              type: 'pronunciation',
              imageUrl: 'https://example.com/images/unit1-boot.png',
              correctAnswer: 'boot',
              points: 5,
            },
            {
              id: 'u1-s5-q7',
              sectionId: 'unit1-sec-1',
              question: 'Say the word: car /ɑː/',
              type: 'pronunciation',
              imageUrl: 'https://example.com/images/unit1-car.png',
              correctAnswer: 'car',
              points: 5,
            },
          ],
        },
        // 6. Listen and write the words you hear. Remember to write a contraction as one word.
        {
          id: 'unit1-sec-6',
          title: 'Listen and write the words you hear. Remember to write a contraction as one word.',
          sectionType: 'listening',
          questionType: 'fill-blank',
          audioUrl: 'https://example.com/audio/unit1-listen-write.mp3',
          questions: [
            {
              id: 'u1-s6-q1',
              sectionId: 'unit1-sec-6',
              question: 'This is ____ in the ____, We ____.',
              type: 'fill-blank',
              correctAnswer: ['my', 'kitchen', "aren't"],
              points: 5,
            },
            {
              id: 'u1-s6-q2',
              sectionId: 'unit1-sec-1',
              question: "That's ____ in the ____.",
              type: 'fill-blank',
              correctAnswer: ['my', 'bedroom'],
              points: 5,
            },
            {
              id: 'u1-s6-q3',
              sectionId: 'unit1-sec-1',
              question: "She's ____, and she ____.",
              type: 'fill-blank',
              correctAnswer: ['my', 'sister', "isn't"],
              points: 5,
            },
            {
              id: 'u1-s6-q4',
              sectionId: 'unit1-sec-1',
              question: 'The ____ in the ____ and ____.',
              type: 'fill-blank',
              correctAnswer: ['cat', 'kitchen', 'sleeping'],
              points: 5,
            },
            {
              id: 'u1-s6-q5',
              sectionId: 'unit1-sec-1',
              question: "She's ____, and ____.",
              type: 'fill-blank',
              correctAnswer: ['my', 'friend', "isn't"],
              points: 5,
            },
            {
              id: 'u1-s6-q6',
              sectionId: 'unit1-sec-1',
              question: 'The ____ next to me ____.',
              type: 'fill-blank',
              correctAnswer: ['person', "isn't"],
              points: 5,
            },
          ],
        },
        // 7. Read Grammar Bank 2A. Then complete the text with the past simple form of the verbs. Use contractions where you can. Listen and check.
        {
          id: 'unit1-sec-7',
          title: 'Read Grammar Bank 2A. Then complete the text with the past simple form of the verbs. Use contractions where you can. Listen and check.',
          sectionType: 'grammar',
          questionType: 'paragraph-fill',
          audioUrl: 'https://example.com/audio/unit1-grammar-bank-2a.mp3',
          passage: `Two summers ago, we ____ (have) a holiday in Scotland. We ____ (drive) there from London, but our car ____ (break) down on the motorway, and we ____ (spend) the first night in Birmingham. When we ____ (get) to Edinburgh, we ____ (go) to our hotel, but they ____ (not can) find our reservation, and they ____ (be) full. We ____ (not know) what to do, but in the end, we ____ (find) a Bed and Breakfast, and we ____ (stay) there for the week. We ____ (see) the castle and ____ (buy) a lot of souvenirs. We ____ (want) to go to Loch Ness, but we ____ (not have) much time, and it ____ (be) quite far away. The weather ____ (not be) very good - it ____ (start) raining on the day we ____ (leave) London, and it never ____ (stop)!`,
          questions: [
            {
              id: 'u1-s7-q1',
              sectionId: 'unit1-sec-1',
              question: 'had',
              type: 'paragraph-fill',
              correctAnswer: 'had',
              points: 2,
            },
            {
              id: 'u1-s7-q2',
              sectionId: 'unit1-sec-1',
              question: 'drove',
              type: 'paragraph-fill',
              correctAnswer: 'drove',
              points: 2,
            },
            {
              id: 'u1-s7-q3',
              sectionId: 'unit1-sec-1',
              question: 'broke',
              type: 'paragraph-fill',
              correctAnswer: 'broke',
              points: 2,
            },
            {
              id: 'u1-s7-q4',
              sectionId: 'unit1-sec-1',
              question: 'spent',
              type: 'paragraph-fill',
              correctAnswer: 'spent',
              points: 2,
            },
            {
              id: 'u1-s7-q5',
              sectionId: 'unit1-sec-1',
              question: 'got',
              type: 'paragraph-fill',
              correctAnswer: 'got',
              points: 2,
            },
            {
              id: 'u1-s7-q6',
              sectionId: 'unit1-sec-1',
              question: 'went',
              type: 'paragraph-fill',
              correctAnswer: 'went',
              points: 2,
            },
            {
              id: 'u1-s7-q7',
              sectionId: 'unit1-sec-1',
              question: "couldn't",
              type: 'paragraph-fill',
              correctAnswer: "couldn't",
              points: 2,
            },
            {
              id: 'u1-s7-q8',
              sectionId: 'unit1-sec-1',
              question: 'were',
              type: 'paragraph-fill',
              correctAnswer: 'were',
              points: 2,
            },
            {
              id: 'u1-s7-q9',
              sectionId: 'unit1-sec-1',
              question: "didn't know",
              type: 'paragraph-fill',
              correctAnswer: "didn't know",
              points: 2,
            },
            {
              id: 'u1-s7-q10',
              sectionId: 'unit1-sec-1',
              question: 'found',
              type: 'paragraph-fill',
              correctAnswer: 'found',
              points: 2,
            },
            {
              id: 'u1-s7-q11',
              sectionId: 'unit1-sec-1',
              question: 'stayed',
              type: 'paragraph-fill',
              correctAnswer: 'stayed',
              points: 2,
            },
            {
              id: 'u1-s7-q12',
              sectionId: 'unit1-sec-1',
              question: 'saw',
              type: 'paragraph-fill',
              correctAnswer: 'saw',
              points: 2,
            },
            {
              id: 'u1-s7-q13',
              sectionId: 'unit1-sec-1',
              question: 'bought',
              type: 'paragraph-fill',
              correctAnswer: 'bought',
              points: 2,
            },
            {
              id: 'u1-s7-q14',
              sectionId: 'unit1-sec-1',
              question: 'wanted',
              type: 'paragraph-fill',
              correctAnswer: 'wanted',
              points: 2,
            },
            {
              id: 'u1-s7-q15',
              sectionId: 'unit1-sec-1',
              question: "didn't have",
              type: 'paragraph-fill',
              correctAnswer: "didn't have",
              points: 2,
            },
            {
              id: 'u1-s7-q16',
              sectionId: 'unit1-sec-1',
              question: 'was',
              type: 'paragraph-fill',
              correctAnswer: 'was',
              points: 2,
            },
            {
              id: 'u1-s7-q17',
              sectionId: 'unit1-sec-1',
              question: "wasn't",
              type: 'paragraph-fill',
              correctAnswer: "wasn't",
              points: 2,
            },
            {
              id: 'u1-s7-q18',
              sectionId: 'unit1-sec-1',
              question: 'started',
              type: 'paragraph-fill',
              correctAnswer: 'started',
              points: 2,
            },
            {
              id: 'u1-s7-q19',
              sectionId: 'unit1-sec-1',
              question: 'left',
              type: 'paragraph-fill',
              correctAnswer: 'left',
              points: 2,
            },
            {
              id: 'u1-s7-q20',
              sectionId: 'unit1-sec-1',
              question: 'stopped',
              type: 'paragraph-fill',
              correctAnswer: 'stopped',
              points: 2,
            },
          ],
        },
      ],
    },
    {
      id: 'exercise-unit2',
      courseId: 'course-1',
      title: 'Unit 2 – People, adjectives and past simple',
      sections: [
        // 1. Listen and read. Match the sentences to the correct picture.
        {
          id: 'unit2-sec-1',
          title: 'Match the sentences to the correct picture',
          sectionType: 'listening',
          questionType: 'picture-choice',
          questions: [
            {
              id: 'u2-s1-q1',
              sectionId: 'unit2-sec-1',
              question: 'She has curly red hair. (choose the correct picture: 1, 2 or 3)',
              type: 'picture-choice',
              options: ['picture 1', 'picture 2', 'picture 3'],
              correctAnswer: 'picture 1',
              points: 5,
            },
            {
              id: 'u2-s1-q2',
              sectionId: 'unit2-sec-1',
              question: 'She has long straight hair. (choose the correct picture: 1, 2 or 3)',
              type: 'picture-choice',
              options: ['picture 1', 'picture 2', 'picture 3'],
              correctAnswer: 'picture 1',
              points: 5,
            },
          ],
        },
        // 2. Write the opposite adjectives. Then listen and check.
        {
          id: 'unit2-sec-2',
          title: 'Write the opposite adjectives',
          sectionType: 'vocabulary',
          questionType: 'fill-sentence',
          wordBank: ['mean', 'unkind', 'hard-working', 'quiet', 'serious', 'extrovert', 'unfriendly', 'stupid'],
          questions: [
            {
              id: 'u2-s2-q1',
              sectionId: 'unit2-sec-1',
              question: 'friendly → ________',
              type: 'fill-sentence',
              correctAnswer: 'unfriendly',
              points: 5,
            },
            {
              id: 'u2-s2-q2',
              sectionId: 'unit2-sec-1',
              question: 'talkative → ________',
              type: 'fill-sentence',
              correctAnswer: 'quiet',
              points: 5,
            },
            {
              id: 'u2-s2-q3',
              sectionId: 'unit2-sec-1',
              question: 'generous → ________',
              type: 'fill-sentence',
              correctAnswer: 'mean',
              points: 5,
            },
            {
              id: 'u2-s2-q4',
              sectionId: 'unit2-sec-1',
              question: 'kind → ________',
              type: 'fill-sentence',
              correctAnswer: 'unkind',
              points: 5,
            },
            {
              id: 'u2-s2-q5',
              sectionId: 'unit2-sec-1',
              question: 'lazy → ________',
              type: 'fill-sentence',
              correctAnswer: 'hard-working',
              points: 5,
            },
            {
              id: 'u2-s2-q6',
              sectionId: 'unit2-sec-1',
              question: 'funny → ________',
              type: 'fill-sentence',
              correctAnswer: 'serious',
              points: 5,
            },
            {
              id: 'u2-s2-q7',
              sectionId: 'unit2-sec-1',
              question: 'clever → ________',
              type: 'fill-sentence',
              correctAnswer: 'stupid',
              points: 5,
            },
            {
              id: 'u2-s2-q8',
              sectionId: 'unit2-sec-1',
              question: 'shy → ________',
              type: 'fill-sentence',
              correctAnswer: 'extrovert',
              points: 5,
            },
          ],
        },
        // 3. Read and listen to the article. Choose the correct answers.
        {
          id: 'unit2-sec-3',
          title: "Read and listen to the article. Choose the correct answers.",
          sectionType: 'reading',
          questionType: 'reading-mcq',
          audioUrl: 'https://example.com/audio/unit2-singles-day.mp3',
          passage: `Singles' Day in Shanghai

The 11th of November is 'Singles' Day' in Shanghai, and every year a dating event takes place where all the single men and women of the city have the chance to meet a partner. Last year, it was so popular that the organizers had to close online registration because there were no more places.

Between 10,000 and 40,000 people attend the event every year. It's held in a district of Shanghai called Thames Town. At least 50 dating agencies take part. They set up stands in the town hall with billboards displaying cards with the height, the date of birth, education, and annual income of thousands of clients. People who did not manage to register for the event organize their own unofficial dating system by writing their names and phone numbers on bits of paper and attaching them to the fence outside the town hall.`,
          questions: [
            {
              id: 'u2-s3-q1',
              sectionId: 'unit2-sec-1',
              question: "People go to Singles' Day to find ____.",
              type: 'reading-mcq',
              options: ['a job', 'a teacher', 'a partner'],
              correctAnswer: 'a partner',
              points: 5,
            },
            {
              id: 'u2-s3-q2',
              sectionId: 'unit2-sec-1',
              question: "Singles' Day takes place ____ the town hall.",
              type: 'reading-mcq',
              options: ['outside', 'inside and outside', 'inside'],
              correctAnswer: 'inside and outside',
              points: 5,
            },
            {
              id: 'u2-s3-q3',
              sectionId: 'unit2-sec-1',
              question: 'There are ____ single people in Shanghai today.',
              type: 'reading-mcq',
              options: ['more', 'the same number of', 'fewer'],
              correctAnswer: 'more',
              points: 5,
            },
          ],
        },
        // 4. Writing a new profile
        {
          id: 'unit2-sec-4',
          title: 'Write a new profile for yourself',
          sectionType: 'writing',
          questionType: 'writing',
          questions: [
            {
              id: 'u2-s4-q1',
              sectionId: 'unit2-sec-1',
              question:
                'Imagine you are a character from a film or TV series. Write five short paragraphs about: name, age, nationality; work/studies and family; physical appearance; personality; hobbies and interests.',
              type: 'writing',
              correctAnswer: '',
              points: 20,
            },
          ],
        },
        // 5. Choose the correct options to complete the sentences
        {
          id: 'unit2-sec-5',
          title: 'Choose the correct options',
          sectionType: 'grammar',
          questionType: 'multiple-choice',
          questions: [
            {
              id: 'u2-s5-q1',
              sectionId: 'unit2-sec-1',
              question: '____ any friends in the USA?',
              type: 'multiple-choice',
              options: ['Are you have', 'You have', 'Do you have'],
              correctAnswer: 'Do you have',
              points: 5,
            },
            {
              id: 'u2-s5-q2',
              sectionId: 'unit2-sec-1',
              question: '"Where ____?" "At the BBC. She\'s an engineer."',
              type: 'multiple-choice',
              options: ['Kim does work', 'does work Kim', 'does Kim work'],
              correctAnswer: 'does Kim work',
              points: 5,
            },
            {
              id: 'u2-s5-q3',
              sectionId: 'unit2-sec-1',
              question: "I'm hungry! ____ something to eat.",
              type: 'multiple-choice',
              options: ["I'm wanting", "I'm want", 'I want'],
              correctAnswer: 'I want',
              points: 5,
            },
          ],
        },
        // 6. Listen and write the words you hear. Remember to write a contraction as one word.
        {
          id: 'unit2-sec-6',
          title: 'Listen and write the words you hear. Remember to write a contraction as one word.',
          sectionType: 'listening',
          questionType: 'fill-blank',
          questions: [
            {
              id: 'u2-s6-q1',
              sectionId: 'unit2-sec-1',
              question: 'This is ____ ____ ____ ____ ____ in the ____ ____ ____. We ____ ____ ____.',
              type: 'fill-blank',
              audioUrl: 'https://example.com/audio/unit2-listen-write-q1.mp3',
              correctAnswer: ['my', 'sister', 'in', 'the', 'kitchen', 'We', "aren't", 'here'],
              points: 5,
            },
            {
              id: 'u2-s6-q2',
              sectionId: 'unit2-sec-1',
              question: "That's ____ ____ in the ____ ____ ____.",
              type: 'fill-blank',
              audioUrl: 'https://example.com/audio/unit2-listen-write-q2.mp3',
              correctAnswer: ['my', 'brother', 'bedroom'],
              points: 5,
            },
            {
              id: 'u2-s6-q3',
              sectionId: 'unit2-sec-1',
              question: "She's ____ ____, and she ____ ____ ____.",
              type: 'fill-blank',
              audioUrl: 'https://example.com/audio/unit2-listen-write-q3.mp3',
              correctAnswer: ['my', 'friend', "isn't", 'here', 'today'],
              points: 5,
            },
            {
              id: 'u2-s6-q4',
              sectionId: 'unit2-sec-1',
              question: 'The ____ in the ____ and ____ ____ ____.',
              type: 'fill-blank',
              audioUrl: 'https://example.com/audio/unit2-listen-write-q4.mp3',
              correctAnswer: ['cat', 'kitchen', 'is', 'sleeping', 'now'],
              points: 5,
            },
            {
              id: 'u2-s6-q5',
              sectionId: 'unit2-sec-1',
              question: "She's ____ ____, and ____ ____ ____.",
              type: 'fill-blank',
              audioUrl: 'https://example.com/audio/unit2-listen-write-q5.mp3',
              correctAnswer: ['my', 'teacher', "isn't", 'here', 'today'],
              points: 5,
            },
            {
              id: 'u2-s6-q6',
              sectionId: 'unit2-sec-1',
              question: 'The ____ ____ next to me ____ ____.',
              type: 'fill-blank',
              audioUrl: 'https://example.com/audio/unit2-listen-write-q6.mp3',
              correctAnswer: ['person', 'sitting', "isn't", 'my', 'friend'],
              points: 5,
            },
          ],
        },
        // 7. Read Grammar Bank 2A. Then complete the text with the past simple form of the verbs. Use contractions where you can. Listen and check.
        {
          id: 'unit2-sec-7',
          title: 'Read Grammar Bank 2A. Then complete the text with the past simple form of the verbs. Use contractions where you can. Listen and check.',
          sectionType: 'grammar',
          questionType: 'paragraph-fill',
          audioUrl: 'https://example.com/audio/unit2-grammar-bank-2a.mp3',
          passage: `Two summers ago, we ____ (have) a holiday in Scotland. We ____ (drive) there from London, but our car ____ (break) down on the motorway, and we ____ (spend) the first night in Birmingham. When we ____ (get) to Edinburgh, we ____ (go) to our hotel, but they ____ (not can) find our reservation, and they ____ (be) full. We ____ (not know) what to do, but in the end, we ____ (find) a Bed and Breakfast, and we ____ (stay) there for the week. We ____ (see) the castle and ____ (buy) a lot of souvenirs. We ____ (want) to go to Loch Ness, but we ____ (not have) much time, and it ____ (be) quite far away. The weather ____ (not be) very good - it ____ (start) raining on the day we ____ (leave) London, and it never ____ (stop)!`,
          questions: [
            {
              id: 'u2-s7-q1',
              sectionId: 'unit2-sec-1',
              question: 'had',
              type: 'paragraph-fill',
              correctAnswer: 'had',
              points: 2,
            },
            {
              id: 'u2-s7-q2',
              sectionId: 'unit2-sec-1',
              question: 'drove',
              type: 'paragraph-fill',
              correctAnswer: 'drove',
              points: 2,
            },
            {
              id: 'u2-s7-q3',
              sectionId: 'unit2-sec-1',
              question: 'broke',
              type: 'paragraph-fill',
              correctAnswer: 'broke',
              points: 2,
            },
            {
              id: 'u2-s7-q4',
              sectionId: 'unit2-sec-1',
              question: 'spent',
              type: 'paragraph-fill',
              correctAnswer: 'spent',
              points: 2,
            },
            {
              id: 'u2-s7-q5',
              sectionId: 'unit2-sec-1',
              question: 'got',
              type: 'paragraph-fill',
              correctAnswer: 'got',
              points: 2,
            },
            {
              id: 'u2-s7-q6',
              sectionId: 'unit2-sec-1',
              question: 'went',
              type: 'paragraph-fill',
              correctAnswer: 'went',
              points: 2,
            },
            {
              id: 'u2-s7-q7',
              sectionId: 'unit2-sec-1',
              question: "couldn't",
              type: 'paragraph-fill',
              correctAnswer: "couldn't",
              points: 2,
            },
            {
              id: 'u2-s7-q8',
              sectionId: 'unit2-sec-1',
              question: 'were',
              type: 'paragraph-fill',
              correctAnswer: 'were',
              points: 2,
            },
            {
              id: 'u2-s7-q9',
              sectionId: 'unit2-sec-1',
              question: "didn't know",
              type: 'paragraph-fill',
              correctAnswer: "didn't know",
              points: 2,
            },
            {
              id: 'u2-s7-q10',
              sectionId: 'unit2-sec-1',
              question: 'found',
              type: 'paragraph-fill',
              correctAnswer: 'found',
              points: 2,
            },
            {
              id: 'u2-s7-q11',
              sectionId: 'unit2-sec-1',
              question: 'stayed',
              type: 'paragraph-fill',
              correctAnswer: 'stayed',
              points: 2,
            },
            {
              id: 'u2-s7-q12',
              sectionId: 'unit2-sec-1',
              question: 'saw',
              type: 'paragraph-fill',
              correctAnswer: 'saw',
              points: 2,
            },
            {
              id: 'u2-s7-q13',
              sectionId: 'unit2-sec-1',
              question: 'bought',
              type: 'paragraph-fill',
              correctAnswer: 'bought',
              points: 2,
            },
            {
              id: 'u2-s7-q14',
              sectionId: 'unit2-sec-1',
              question: 'wanted',
              type: 'paragraph-fill',
              correctAnswer: 'wanted',
              points: 2,
            },
            {
              id: 'u2-s7-q15',
              sectionId: 'unit2-sec-1',
              question: "didn't have",
              type: 'paragraph-fill',
              correctAnswer: "didn't have",
              points: 2,
            },
            {
              id: 'u2-s7-q16',
              sectionId: 'unit2-sec-1',
              question: 'was',
              type: 'paragraph-fill',
              correctAnswer: 'was',
              points: 2,
            },
            {
              id: 'u2-s7-q17',
              sectionId: 'unit2-sec-1',
              question: "wasn't",
              type: 'paragraph-fill',
              correctAnswer: "wasn't",
              points: 2,
            },
            {
              id: 'u2-s7-q18',
              sectionId: 'unit2-sec-1',
              question: 'started',
              type: 'paragraph-fill',
              correctAnswer: 'started',
              points: 2,
            },
            {
              id: 'u2-s7-q19',
              sectionId: 'unit2-sec-1',
              question: 'left',
              type: 'paragraph-fill',
              correctAnswer: 'left',
              points: 2,
            },
            {
              id: 'u2-s7-q20',
              sectionId: 'unit2-sec-1',
              question: 'stopped',
              type: 'paragraph-fill',
              correctAnswer: 'stopped',
              points: 2,
            },
          ],
        },
      ],
    },
    {
      id: 'exercise-unit3',
      courseId: 'course-1',
      title: 'Unit 3 – Practical English & Social Phrases',
      sections: [
        // 1. Watch the Social English phrases. Then record yourself saying them.
        {
          id: 'unit3-sec-1',
          title: 'Watch the Social English phrases. Then record yourself saying them.',
          sectionType: 'speaking',
          questionType: 'video-recording',
          videoUrl: 'https://example.com/video/unit3-episode2-restaurant-problems.mp4',
          description: 'EPISODE 2 - Practical English - Restaurant problems - Social English phrases',
          questions: [
            {
              id: 'u3-s1-q1',
              sectionId: 'unit3-sec-1',
              question: 'Record yourself saying the Social English phrases from the video.',
              type: 'video-recording',
              correctAnswer: '',
              points: 0, // Không tính điểm, chỉ luyện tập
            },
          ],
        },
        // 2. Watch the Social English phrases. Then record yourself saying them.
        {
          id: 'unit3-sec-2',
          title: 'Watch the Social English phrases. Then record yourself saying them.',
          sectionType: 'speaking',
          questionType: 'video-recording',
          videoUrl: 'https://example.com/video/unit3-episode3-social-phrases.mp4',
          description: 'EPISODE 3 - Practical English - Social English phrases',
          questions: [
            {
              id: 'u3-s2-q1',
              sectionId: 'unit3-sec-2',
              question: 'Record yourself saying the Social English phrases from the video.',
              type: 'video-recording',
              correctAnswer: '',
              points: 0, // Không tính điểm, chỉ luyện tập
            },
          ],
        },
      ],
    },
  ];

  // Mock Quizzes
  const quizzes: Quiz[] = [
    {
      id: 'quiz-1',
      courseId: 'course-1',
      title: 'Midterm Quiz - Tiếng Anh 1',
      description: 'Bài kiểm tra giữa kỳ cho học phần Tiếng Anh 1',
      sections: [
        {
          id: 'quiz-1-section-1',
          title: 'Grammar Section',
          description: 'Kiểm tra kiến thức ngữ pháp cơ bản',
          sectionType: 'grammar',
          questionType: 'multiple-choice',
          questions: [
            {
              id: 'quiz-1-q1',
              sectionId: 'quiz-1-section-1',
              question: 'What is the past tense of "go"?',
              type: 'multiple-choice',
              options: ['goed', 'went', 'gone', 'going'],
              correctAnswer: 'went',
              points: 10,
            },
            {
              id: 'quiz-1-q2',
              sectionId: 'quiz-1-section-1',
              question: 'Choose the correct form: "She _____ to school every day."',
              type: 'multiple-choice',
              options: ['go', 'goes', 'going', 'went'],
              correctAnswer: 'goes',
              points: 10,
            },
            {
              id: 'quiz-1-q3',
              sectionId: 'quiz-1-section-1',
              question: 'Which sentence is in Present Continuous tense?',
              type: 'multiple-choice',
              options: [
                'I play football.',
                'I am playing football.',
                'I played football.',
                'I will play football.'
              ],
              correctAnswer: 'I am playing football.',
              points: 10,
            },
          ],
        },
        {
          id: 'quiz-1-section-2',
          title: 'Vocabulary Section',
          description: 'Kiểm tra vốn từ vựng',
          sectionType: 'vocabulary',
          questionType: 'multiple-choice',
          questions: [
            {
              id: 'quiz-1-q4',
              sectionId: 'quiz-1-section-2',
              question: 'What is the meaning of "beautiful"?',
              type: 'multiple-choice',
              options: ['xấu', 'đẹp', 'lớn', 'nhỏ'],
              correctAnswer: 'đẹp',
              points: 10,
            },
            {
              id: 'quiz-1-q5',
              sectionId: 'quiz-1-section-2',
              question: 'Choose the synonym of "happy":',
              type: 'multiple-choice',
              options: ['sad', 'glad', 'angry', 'tired'],
              correctAnswer: 'glad',
              points: 10,
            },
            {
              id: 'quiz-1-q6',
              sectionId: 'quiz-1-section-2',
              question: 'What is the opposite of "hot"?',
              type: 'multiple-choice',
              options: ['warm', 'cold', 'cool', 'freezing'],
              correctAnswer: 'cold',
              points: 10,
            },
          ],
        },
        {
          id: 'quiz-1-section-3',
          title: 'Reading Comprehension',
          description: 'Đọc hiểu đoạn văn và trả lời câu hỏi',
          sectionType: 'reading',
          questionType: 'reading-mcq',
          passage: 'Tom is a student. He goes to school every day. He likes English very much. In the morning, he reads books. In the afternoon, he does homework. He is a good student.',
          questions: [
            {
              id: 'quiz-1-q7',
              sectionId: 'quiz-1-section-3',
              question: 'What does Tom do every day?',
              type: 'reading-mcq',
              options: ['He plays games', 'He goes to school', 'He watches TV', 'He goes shopping'],
              correctAnswer: 'He goes to school',
              points: 15,
            },
            {
              id: 'quiz-1-q8',
              sectionId: 'quiz-1-section-3',
              question: 'What does Tom like?',
              type: 'reading-mcq',
              options: ['Math', 'English', 'Science', 'History'],
              correctAnswer: 'English',
              points: 15,
            },
            {
              id: 'quiz-1-q9',
              sectionId: 'quiz-1-section-3',
              question: 'When does Tom read books?',
              type: 'reading-mcq',
              options: ['In the morning', 'In the afternoon', 'In the evening', 'At night'],
              correctAnswer: 'In the morning',
              points: 15,
            },
          ],
        },
        {
          id: 'quiz-1-section-4',
          title: 'Writing Section',
          description: 'Viết câu và đoạn văn',
          sectionType: 'writing',
          questionType: 'writing',
          questions: [
            {
              id: 'quiz-1-q10',
              sectionId: 'quiz-1-section-4',
              question: 'Write a sentence using Present Simple tense.',
              type: 'writing',
              correctAnswer: '',
              points: 20,
            },
            {
              id: 'quiz-1-q11',
              sectionId: 'quiz-1-section-4',
              question: 'Describe your daily routine in 3-4 sentences.',
              type: 'writing',
              correctAnswer: '',
              points: 25,
            },
            {
              id: 'quiz-1-q12',
              sectionId: 'quiz-1-section-4',
              question: 'Write about your favorite hobby and why you like it.',
              type: 'writing',
              correctAnswer: '',
              points: 25,
            },
          ],
        },
      ],
      timeLimit: 60,
      passingScore: 60,
    },
    {
      id: 'quiz-2',
      courseId: 'course-1',
      title: 'Final Exam - Tiếng Anh 1',
      description: 'Bài thi cuối kỳ cho học phần Tiếng Anh 1',
      sections: [
        {
          id: 'quiz-2-section-1',
          title: 'Grammar Advanced',
          description: 'Ngữ pháp nâng cao',
          sectionType: 'grammar',
          questionType: 'multiple-choice',
          questions: [
            {
              id: 'quiz-2-q1',
              sectionId: 'quiz-2-section-1',
              question: 'Choose the correct conditional sentence:',
              type: 'multiple-choice',
              options: [
                'If I was you, I would go.',
                'If I were you, I would go.',
                'If I am you, I will go.',
                'If I be you, I go.'
              ],
              correctAnswer: 'If I were you, I would go.',
              points: 15,
            },
            {
              id: 'quiz-2-q2',
              sectionId: 'quiz-2-section-1',
              question: 'Which sentence uses passive voice correctly?',
              type: 'multiple-choice',
              options: [
                'The book was read by me.',
                'The book read by me.',
                'The book is read by me yesterday.',
                'The book reading by me.'
              ],
              correctAnswer: 'The book was read by me.',
              points: 15,
            },
            {
              id: 'quiz-2-q3',
              sectionId: 'quiz-2-section-1',
              question: 'Complete: "I have _____ this movie three times."',
              type: 'multiple-choice',
              options: ['see', 'saw', 'seen', 'seeing'],
              correctAnswer: 'seen',
              points: 15,
            },
          ],
        },
        {
          id: 'quiz-2-section-2',
          title: 'Fill in the Blanks',
          description: 'Điền từ vào chỗ trống',
          sectionType: 'vocabulary',
          questionType: 'fill-blank',
          questions: [
            {
              id: 'quiz-2-q4',
              sectionId: 'quiz-2-section-2',
              question: 'Complete the sentence: "I _____ to the store yesterday."',
              type: 'fill-blank',
              correctAnswer: 'went',
              points: 10,
            },
            {
              id: 'quiz-2-q5',
              sectionId: 'quiz-2-section-2',
              question: 'Fill in: "She _____ English for five years."',
              type: 'fill-blank',
              correctAnswer: 'has studied',
              points: 10,
            },
            {
              id: 'quiz-2-q6',
              sectionId: 'quiz-2-section-2',
              question: 'Complete: "They _____ playing football when it started raining."',
              type: 'fill-blank',
              correctAnswer: 'were',
              points: 10,
            },
          ],
        },
        {
          id: 'quiz-2-section-3',
          title: 'Listening Comprehension',
          description: 'Nghe hiểu (giả lập - không có audio thực)',
          sectionType: 'listening',
          questionType: 'listening',
          audioUrl: 'https://example.com/listening-audio.mp3',
          questions: [
            {
              id: 'quiz-2-q7',
              sectionId: 'quiz-2-section-3',
              question: 'What did the speaker say about the weather?',
              type: 'listening',
              options: ['It is sunny', 'It is raining', 'It is cloudy', 'It is snowing'],
              correctAnswer: 'It is raining',
              points: 20,
            },
            {
              id: 'quiz-2-q8',
              sectionId: 'quiz-2-section-3',
              question: 'Where did the conversation take place?',
              type: 'listening',
              options: ['At a restaurant', 'At a school', 'At a park', 'At a library'],
              correctAnswer: 'At a restaurant',
              points: 20,
            },
            {
              id: 'quiz-2-q9',
              sectionId: 'quiz-2-section-3',
              question: 'What time did they meet?',
              type: 'listening',
              options: ['8:00 AM', '12:00 PM', '6:00 PM', '9:00 PM'],
              correctAnswer: '6:00 PM',
              points: 20,
            },
          ],
        },
      ],
      timeLimit: 90,
      passingScore: 70,
    },
  ];

  saveCourses(courses);
  saveExercises(exercises);
  saveQuizzes(quizzes);
};

